### ISSUE TITLE
Url 링크로 접근하는 경우 layout이 변경되면 첫번째 요청시 라인차트가 그려지지 않음

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#100]
Url 링크로 접근하는 경우 layout이 변경되면 첫번째 요청시 라인차트가 그려지지 않음
새로 고침하면 그려짐.

다시 다른 layout 조건으로 요청해도 동일함. 한번 더 요청되어야 그려짐. 

http://demo.scouterapm.com:6188/extweb/index.html#/paper?&address=demo.scouterapm.com&port=6188&realtime=false&xlogElapsedTime=8000&objects=-796172661,-1180057655,-1502713930&from=1538793200412&to=1538793500412&layout=Only-Web-Dashboard

http://demo.scouterapm.com:6188/extweb/index.html#/paper?&address=demo.scouterapm.com&port=6188&realtime=false&xlogElapsedTime=8000&objects=-796172661,-1180057655,-1502713930&from=1538793200412&to=1538793500412&layout=Main-Dashboard

**Comment by mindplates** [comment]
개발 브렌치에 해당 버그 수정하였습니다. 다음 릴리즈때 반영하겠습니다.

**Comment by gunlee01** [comment]
라인차트는 그려지나 아래와 같이 최근 5분간을 요청하면, 미래 시간까지 보여준다.
요청시간은 오후 4시47분 ~ 52분이지만 화면에 17시17분까지 나옴.

http://localhost:3000/extweb/index.html#/paper?&address=demo.scouterapm.com&port=6188&realtime=false&xlogElapsedTime=8000&instances=-796172661,-1180057655,-1502713930&from=1539071257793&to=1539071557793&layout=Only-Web-Dashboard

![image](https://user-images.githubusercontent.com/6788732/46654639-54c55280-cbe4-11e8-8ac4-e412ec6ba178.png)

**Comment by mindplates** [comment]
요건 요번에 수정한 내용입니다만, 
설정의 최소 조회 범위가 10분인데, 5분을 요청하는 경우, 10분으로 보여주도록 개선한 내용입니다.
5분을 보여주려면, 최소 조회 범위를 5분으로 변경하셔야 합니다.
