### ISSUE TITLE
paper 2.1.320 특이사항 문의드립니다.

### ISSUE THREAD

**Issue by gogomasaru** [mindplates/scouter-paper#103]
paper 2.1.320 릴리즈 후 테스트 했는데 특이사항이 있어 문의드립니다.
scouter 서버 3개 정도 환경으로 구성해서 테스트 하는데 1대에서 설치 후 object를 계속 못가지고 와서 500 에러 발생했습니다. (3개 OS 및 자바버전 등 설정은 동일하고, 3대 영향없는 각각 환경/서버입니다.)
그 비정상 서버 조치하려고 크롬 브라우저 캐시를 삭제 했더니 layout preset이 삭제 되어 문의드립니다.

- 비정상 서버 -
1. 스카우터 2.0.1 설치
2. paper 2.1.320 설치
3. papers (대쉬보드) 화면이 없었음. 아무 그래프가 없는 빈 디폴트 화면
4. layout preset은 있었음
5. object 정보를 못가지고 와서 브라우저 캐시 삭제 했더니 layout preset 삭제됨.
(1대 object 정보를 못가지고 와서 500 에러 발생했었음.)
 - object preset은 있음
6. 정상 서버 layout preset도 삭제됨.

- object 정보 못가져왔을때 버전 - 
1. scouter 2.0 + 2.1.308 정상
2. scouter 2.1 + 2.1.308 정상
3. scouter 2.1 + 2.1.320 비정상 500에러

추가 문의 : layout preset을 export 해서 로컬PC에 저장 방법 없을까요?

**Comment by gunlee01** [comment]
시스템적으로 layout과 preset은 브라우저 캐시와는 관련이 없습니다.
저장된 layout과 preset 목록은 scouter webapi를 통해서 scouter server에 저장이 됩니다. 
브라우저의 로컬스토리지에 저장되는 부분은 접속할 서버 정보, 폰트등의 설정, 그리고 현재의 layout 형태, 선택한 object 목록(preset) 등 입니다.
만약 브라우저의 로컬 스토리지를 날렸다면 현재 layout등은 초기화 됩니다.
(단 서버에 저장된 layout, preset은 유지됩니다. 이를 로드하면 브라우저에 다시 적용됩니다.)

500에러는 서버 로그를 같이 봐야 될 것 같습니다.
에러 발생 시점의 서버 로그를 같이 올려주시면 도움이 될듯 합니다.
(browser error 응답로그, scouter webapp 로그, scouter server 로그.)

layout, preset은 서버에 저장되니 특별히 필요치 않아 export 기능은 없는데요,
꼭 필요하다면 현재 로드된 값들은 local storage에 있으니 크롬의 경우라면 개발자 도구의 application 탭에서 local storage 항목을 복사해 사용할 수 있습니다.

**Comment by mindplates** [comment]
이건은 재발하신다면  우선  서버 로그 (logs 폴더 하위에 있습니다.)를 좀 주시면 더 진행할 수 있을 것 같구요. 추가 문의에서 제안해주신 기능과, 설정을 지우는 기능 (현재 개발자 도구로 지우시는 부분)을 함께 추가하는 것을 검토하겠습니다!
