### ISSUE TITLE
Profile 창에서 연결된 api call 또는 비동기 thread xlog를 링크하는 기능.

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#104]
## XLog 의 속성값 설명
 * txid - 현재 xlog id
 * caller - 이 xlog를 호출한 xlog의 id
 * gxid - 가장 먼저 시작된 xlog id

txid, gxid가 같은 경우는 최초 invoke된 요청임.

### 동작
profile화면 상단의 xlog 값이 보여지는 곳에 각 id(txid,gxid,caller)값이 있는경우 이를 보여주어서 이를 클릭하면, caller나 gxid의 xlog 창이 열린다.

## Profile step 에서 링크할 항목
연결된 xlog를 클릭하면 연결된 xlog를 열어준다.

 * step에 txid 항목 값이 있는 경우에 이를 링크한다.
   단 stepType = 14(THREAD_CALL_POSSIBLE)인 경우에는 thread 값이 1일때만. (0인 경우는 txid는 생성되었으나 실제 사용되지 않은 경우임. 이 경우에는 이 step을 화면에 보여줄 필요도 없다.)

### 동작
이 step을 누르면 연결된 xlog를 열어준다.

**Comment by mindplates** [comment]
2.2.326 버전에 적용되었습니다!
