### ISSUE TITLE
[branch controller] 외부 연동 step 시인성 개선 요청

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#126]
![image](https://user-images.githubusercontent.com/6788732/50570650-3ed7c000-0dd6-11e9-8daa-67ab77ed4c70.png)

**SQL**과 같은 외부 연동은 **API CALL**등과 마찬가지로 Profile에서 가장 중요하게 보여져야 하므로
좌측의 STEP명(METHOD, SQL, MSG... 같은)의 색상이 눈에 띠게 변경하면 좋겠습니다.

* 대상
  - "stepTypeName"이 `SQL`로 시작하는 경우
  - "stepType": `17` 이고 
    - mainValue에 `[REDIS]`가 포함 되는 경우
    - mainValue에 `[KAFKA]`가 포함 되는 경우
    - mainValue에 `[RABBIT]`가 포함 되는 경우

**Comment by gunlee01** [comment]
추가로 지연 포인트를 찾기위한 DUMP Step의 이름도 Bold 처리 등으로 눈에 잘띠면 좋을 듯 합니다.

**Comment by mindplates** [comment]
개선하였습니다~
