### ISSUE TITLE
[branch controller] 좌측 서랍 메뉴 overlay와 pin 모드 지원

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#129]
현재 pin mode로만 동작하는데 mouse over시에 overlay로 동작하면 좋을 것 같습니다.
mouse over시에 overlay로 나오고, mouse out시에 다시 들어가는 형태.

혹은 클릭시에 기본이 overlay이고 pin 버튼이 따로 존재하는 방식도 괜찮겠네요.

서랍메뉴를 반복해서 클릭하는 경우 어떤 경우는 페이퍼 화면이 우측으로 밀리고 어떤 경우는 화면 사이즈가 줄어드는데 확실한 케이스를 모르겠네요.
아래 영상 참고하세요.
https://youtu.be/v5tiwz3bsHA
**이게 실시간인 경우는 괜찮은데 history로 해놓고 하면 그런듯 합니다.**

**Comment by mindplates** [comment]
개선하였습니다!
