### ISSUE TITLE
settings나 메인화면에서 오브젝트 선택없이 paper 메뉴 클릭하면 xlog list 창이 뜨면서 404 에러가 나는 현상

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#41]
* 재현경로
 - http://localhost:3000 접속
 - paper 메뉴 선택
 - 404 에러 발생

![image](https://user-images.githubusercontent.com/6788732/39407151-d1444b80-4bfc-11e8-9793-4159d055cfcc.png)

**Comment by mindplates** [comment]
1.6 버전에서 수정 예정입니다.
