### ISSUE TITLE
기간 선택시 시간 파라미터가 오전 시간이 되는 현상

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#42]
오후 21시경으로 조회를 하면 오전 09시로 파라미터가 생성되는 현상.

![image](https://user-images.githubusercontent.com/6788732/39407176-0e4ac02c-4bfd-11e8-8f7d-59a71ff6d2f1.png)

**Comment by mindplates** [comment]
1.6 버전에서 수정예정입니다.
