### ISSUE TITLE
파라미터를 통한 레이아웃 세팅 기능 및 xlog 높이 조정 기능 추가.

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#43]
### 1. 파라미터를 통한 레이아웃 세팅 (레이아웃 명 또는 layouts, boxes 파라미터를 통해.)
 - 기본 레이아웃 몇개를 제공하여 그 레이아웃을 이름으로 레이아웃을 세팅하거나 하는 기능
   (최초 사용자의 경우나 헤드리스 브라우저로 그리는 경우, 설정한 layout이 없으므로 화면이 그려지지 않는 문제가 있음)

### 2. xlog 높이를 파라미터로 조정가능하도록
 - 헤드리스 브라우저로 그리는 경우에 기본 2초로만 그려지는 현상 개선

### * 아래 이미지는 헤드리스로 생성된 이미지이며 xlog가 2초로 고정됨.

![paper2](https://user-images.githubusercontent.com/6788732/39407240-a03b308e-4bfd-11e8-92cc-f193a237120f.png)

**Comment by mindplates** [comment]
1.6
