### ISSUE TITLE
인스턴스 선택에서 스카우터 서버를 변경하면 Server는 갱신되는데 instance명은 갱신되지 않고 그대로 있음. Sever명을 눌러야 그때 변경됨.

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#45]
* 인스턴스 선택시 스카우터 서버를 변경하면 Server는 갱신되는데 instance명은 갱신되지 않고 그대로 있음. Sever명을 눌러야 그때 변경됨.

**Comment by mindplates** [comment]
development 브런치에 개선, 다음 릴리즈에 포함됩니다.
