### ISSUE TITLE
paper v1.6.218 에서 스카우터 로그인 주소가 undefined로 나오는 현상 

### ISSUE THREAD

**Issue by kranian** [mindplates/scouter-paper#46]
안녕하세요? 스카우터 웹 버전을 알게 되어 테스트 하고 있는데. 신규 pre-release 버전에 아래와 같은 스카우터 
주소 설정 과 로그인이 안되는 현상이 확인되어 올립니다.  
 
# scouter 버전 v1.8.5
 - 스카우터 컬렉터 서버 접근 확인 
![image](https://user-images.githubusercontent.com/18545293/39610217-b6ad4ad4-4f89-11e8-86dd-c8eea6992b0f.png)

# 사용한 크롬 버전 63.0.3239.108(공식 빌드) (64비트)
![image](https://user-images.githubusercontent.com/18545293/39610321-66c7da74-4f8a-11e8-8c72-eb1f34eccb97.png)

# paper 버전 v.1.6.218
![image](https://user-images.githubusercontent.com/18545293/39610096-f0a986ae-4f88-11e8-818b-f0bad19dce4a.png)
# 로그인 화면 로그인 버튼 클릭시 오류  
![image](https://user-images.githubusercontent.com/18545293/39610257-0e5e93aa-4f8a-11e8-9c7a-1d9e01020460.png)

 # 설정 화면 add server 버튼을 클릭해도 반응이 없습니다.  
![image](https://user-images.githubusercontent.com/18545293/39610272-349f3254-4f8a-11e8-9875-1f2e59c96eb0.png)

**Comment by kranian** [comment]
- 내용 부분에 오타가 있어 재수정을 했습니다.

**Comment by mindplates** [comment]
우선 Settings 아래에 보면, Edit 버튼이 있습니다. 해당 버튼을 클릭한 후에 Server 정보를 다시 추가해보시겠어요~? 우선 문제는 Settings를 한번 저장하시면 해결 될 것이라고 생각됩니다.

그리고 혹시 이전 버전에서 업그레이드하신 것인지? 아니면 처음부터 해당 버전을 사용하신 것인지 알려주시면 버그를 찾는데 도움이 될 것 같습니다.
그리고 가능하시다면 위에 개발자 도구에서 Application 탭에 보시면 local storage 정보가 있을텐데요, 해당 내용 알려주셔도 도움이 많이 될 듯 합니다.

감사합니다.

**Comment by kranian** [comment]
처음 설치해 사용 해봤습니다 처음부터 해당 버전을 가지고 해봤습니다 그리고 말씀 하신 부분은 참고해서해서 다시 피드백 올리겠습니다 
지금은 연휴라 못하고 차주 중으로 확인 후 올리겠습니다

**Comment by kranian** [comment]
- 알려 주신 대로 수정을 하면 수정 내용이 application local storage 부에 저장이 됩니다. 하지만 해당 내용이 적용은 되지가 안네요

![image](https://user-images.githubusercontent.com/18545293/39744325-d4850274-52de-11e8-9232-9eecf1f7a17d.png)

**Comment by mindplates** [comment]
답변이 늦어 죄송합니다.
1.6 버전으로 처음 사용하는 경우, 로그인 부분이 처리되지 않는 버그가 있어 해당 부분을 수정하여 다시 릴리즈 하였습니다. 제보 감사합니다. 큰 도움이 되었습니다.
1.7.225 버전을 다운로드하셔서 다시 시도해보시면 정상 동작할 것 입니다.
