### ISSUE TITLE
쿼리 변수 바인딩이 잘못되는 문제

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#63]
쿼리의 바인드 변수 외에 scouter가 쿼리의 normalization을 위해 리터럴 부분(바인드 변수 처리되지 않은 문자부분 및 숫자부분)을 자체적으로 변수 처리한 부분이 제대로 처리 되지 않는 문제.

**Comment by mindplates** [comment]
샘플이나 자체적으로 변수 처리하는 방식을 알려주세요.

**Comment by gunlee01** [comment]
PR proposed.

**Comment by gunlee01** [comment]
@mindplates 리터럴 변수가 내부적으로 처리된 부분은
순서대로 @{1} @{2} 로 들어갑니다.
(문자열인 경우는 '@{1}' 처럼 홑따옴표가 양쪽으로 붙어요.)
