### ISSUE TITLE
각 차트에 대표 objType 아이콘 표시 

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#72]
각 차트에 대표 objType 아이콘 표시

**Comment by mindplates** [comment]
흠...

**Comment by mindplates** [comment]
차트 제목 앞에 아이콘(들)이 표시되도록 변경되었습니다. 더불어 여러 패밀리의 매트릭이 하나의 차트에 있는 경우, 패밀리 명이 함께 출력되도록 변경되었습니다.
개발 브렌치를 확인해주세요!
