### ISSUE TITLE
마우스 오버시에 차트의 값이 나오지 않는 현상

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#74]
데모사이트로 접속해서 Layout을 scouter-demo-complex-01, preset을 scouter-demo-all로 하는 경우, 
일부 페이퍼에 아이콘이 없습니다. 그리고 아이콘이 없는 경우 마우스 오버시에 해당 카운터의 값을 보여주는 팝업이 보여지지 않아요.

추가로 기본 Type의 경우에는 이미 정해진 아이콘이 있어 icon이 null 인데 이 경우 아이콘명은 name의 값을 사용하면 됩니다.

**Comment by mindplates** [comment]
우선 그래프의 툴팁이 안보이는 이유는, 이번 버전 변경에 따라 라인 그래프를 그리는 키에 family 타입이 추가가 되었고, 기존의 layout에는 family 타입이 없이 저장되어 있는 상태라, 보이지가 않는 현상이 있네요.

해당 부분을 layout을 불러온 후에 마이그레이션 개념으로 family name을 추가해줄 수 있을까 고민해보았는데, 동일한 카운터 이름 등이 존재하는 경우가 있을 수 있어, 완전하게 처리할 수 없을 것 같습니다.

이에 layout manager 목록에서 지원되지 않는(family name이 없는) 경우 deprecated 표시되도록 기능을 추가했습니다.

아이콘은 스카우터 클라이언트 파일을 대충 뒤져봤는데, 없어서..
혹시 가능하시면 해당 아이콘 파일을 묶어서 mindplates@gmail.com으로 메일 주실 수 있으실까요?

**Comment by gunlee01** [comment]
https://github.com/scouter-project/scouter/tree/master/scouter.client/icons/object

스카우터 클라이언트의 아이콘 경로입니다.

**Comment by gunlee01** [comment]
@mindplates 
최신소스를 scouter demo 서버로 연결하고
Layout을 demo-complex-01, preset을 scouter-demo-all로 하는 경우
TPS등의 아이콘이 tomcat이 나오지 않고 jetty로 나옵니다.

**Comment by mindplates** [comment]
개발에 수정되었습니다.
