### ISSUE TITLE
실시간 알림 조회 인터벌 개선 요청

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#75]
알림의 조회 인터벌은 카운터의 조회 인터벌과 다른 값을 사용하는게 좋을 것 같습니다.
인터벌은 30초~1분 정도면 충분할 것 같습니다.

**Comment by mindplates** [comment]
변경하려고 보니, 현재 알림이 실시간 데이터 주기와 함께 동작하고 있는 문제가 함께 보입니다.
이 문제로 실시간 조회 모드가 아니면, 알림이 조회가 안되는 문제가 있어보여서,
이 문제를 향후 함께 처리하도록 하겠습니다.
서버가 세팅되었는지의 여부, 로그인 상태 여부, 알림 조회의 시작점을 찾는게 생각보다 일이 좀 있네요.

**Comment by mindplates** [comment]
개발 브렌치에 개선하였습니다. 더불어 옵션에 alert interval을 추가하였습니다.
