### ISSUE TITLE
기본값 조절

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#76]
기본값에 대해 논의
 - 기본 조회 기간 등.

**Comment by mindplates** [comment]
기본 설정 값을 변경하였습니다.
더불어 변경 버튼을 못 찾으시는 분들이 있는 것 같아, 
설정 화면 상단에 버튼을 추가하였고, 
하단에 설정 초기화 링크 버튼을 추가하였습니다.
