### ISSUE TITLE
Layout 로드시 paper에 (Tomcat paper가 아닌데도) Tomcat이 붙어있는 문제.

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#86]
Layout 로드시에 mysql 메트릭만 있는 paper에 tomcat, mysql로 tomcat 명칭이 붙어 있음.
* 재현 (데모시스템으로 접속하여)
 - Demo-system-main-dashboard 로드
 - 이후 Demo-system-MySQL-dashboard 로드.
   - 이때 Paper의 라벨이 이상함.
 - 다시 Demo-system-main-dashboard 로드
   - 이때에도 Paper의 라벨이 이상함
 - 이런 경우 해당 Paper에 최근 10분 데이터가 조회 되지 않는다.

**Comment by gunlee01** [comment]
브라우저를 새로 고침해야 제대로 나옴.

**Comment by mindplates** [comment]
해당 버그 개발 브렌치에 수정하여 커밋하였습니다.
