### ISSUE TITLE
토폴로지에서 브라우저 새로고침시 에러 발생.

### ISSUE THREAD

**Issue by gunlee01** [mindplates/scouter-paper#91]
![image](https://user-images.githubusercontent.com/6788732/46252936-8c791f80-c4ab-11e8-8c48-88b0d9aa5f37.png)

**Comment by mindplates** [comment]
제 환경에서는 위 케이스가 잘 안나와서 현재 확인을 못해봤습니다.
다만 코드만 보고, 우선 에러가 나지않도록 코드는 수정해서 커밋했습니다.
