### ISSUE TITLE
paper 2.0 특이사항 확인 부탁드립니다.

### ISSUE THREAD

**Issue by gogomasaru** [mindplates/scouter-paper#93]
안녕하세요. 이번에 나온 scouter와 paper 2.0 설치했습니다.
1.9에서는 안보이던 현상이 있어 문의드립니다.

1. 그래프가 active speed 이후 없어짐.
![2](https://user-images.githubusercontent.com/26616377/46272829-d33f4600-c58d-11e8-96d2-6cab7c9be0b3.JPG)
따라서, 기존에 사용하는 layout이 deprecate라고 표시됩니다.
![1](https://user-images.githubusercontent.com/26616377/46272832-d5a1a000-c58d-11e8-947c-d4becd80d99b.JPG)

2.  object preset 저장안됩니다.

3.  object 아이콘이 전부 동일함. (육각면체)

4. mem, cpu 그래프 안나옵니다.
클라이언트 프로그램에서는 잘나옵니다.

설치 및 세팅 방법은 1.9와 동일하게 extweb하위에 paper 파일 압축해제 했습니다.

**Comment by mindplates** [comment]
안녕하세요.

우선 말씀주신 내용과 증상이 스카우터 서버가 2.0이 아닐때와 유사한면이 있습니다.
크롬에서 새로고침하시고, 서버로 날라가는 요청 중에 
/server, /counter-model 이라는 요청이 있습니다. 그 요청에 대한 응답 정보를 함께 주실 수 있으실까요~?
해당 정보를 좀 봐야 정확히 원인을 알 수 있을 것 같습니다.

**Comment by gogomasaru** [comment]
제 세팅대로 했을때 counter-model에 401응답이였습니다. server는 200.
혹시나 해서 설정된 ID/passwd + 토큰인증 제거하고 (인증없이) 했을 경우 매트릭 목록 전부 나오고 http 200 나옵니다. 하지만 인증은 사용해야 되서, 내일 쿠키 등 다른인증 방식으로 해도 동일한지 테스트 해보겠습니다

1, 2, 4 정상

3. 아이콘은 여전히 흰색 육각면체
추가 : object preset도 동작합니다. (인증제거)
인증으로 했을때 안되는 기능이 있는것 같습니다. 토플로지 줌이나,
object에 linux, jboss, datasource가 안보였는데 인증없이 하니 보입니다.

**Comment by mindplates** [comment]
우선 자세히 설명해주시고, 테스트 해주셔서 원인을 찾을 수 있었습니다.
로그인 전에 카운터 데이터를 가져오는 문제로 인해 발생하였으며, 스카우터 서버를 2개 이상 사용하는 경우에는, 스카우터 서버를 변경할때 마다 카운터 정보를 가져오기 때문에, 제가 테스트하는 환경에서 빨리 찾지를 못했는데, 증상을 자세하게 알려주셔서 수정할 수 있었네요.

방금 2.1 버전을 다시 릴리즈 하였습니다. 번거로우시겠지만, 페이퍼만 다시 다운로드하셔서 잘 되는지 확인 부탁드려도 될까요?

많은 도움이 되었습니다. 다시 한번 감사드립니다.

**Comment by gogomasaru** [comment]
빠른 조치 감사합니다.
2.1로 테스트 결과 말씀드립니다.

- 2.1 설치 토큰인증 설정 후 테스트
1. 매트릭 컴포넌트 모두 정상적으로 보입니다.
2. object preset 저장 잘됩니다.
3. 그래프 위에 팝업cnt 잘 나옵니다.
4. layout 잘됩니다.
5. oject 정보 나옵니다. (batct, datasource, jboss)

- 2.1 설치 후 특이사항
1. 토플로지가 나오지 않습니다. node, 링크 카운트는 올라갑니다.
![3](https://user-images.githubusercontent.com/26616377/46328588-2aebb900-c643-11e8-9e49-bad968c526d0.JPG)

- 추가 문의
 object 아이콘은 정육각형만 되어있습니다. 동영상처럼 톰캣 등 아이콘이 아님.
![1](https://user-images.githubusercontent.com/26616377/46328598-3e971f80-c643-11e8-8501-8235f15b3451.JPG)
![2](https://user-images.githubusercontent.com/26616377/46328600-4060e300-c643-11e8-87fa-f119868922a2.JPG)

**Comment by gunlee01** [comment]
@gogomasaru 
일단 토폴로지는 scouter agent에 설정을 먼저 확인해 보세요. 인터랙션 카운터가 기본 설정으로는 disable 입니다.
https://mindplates.github.io/scouter-paper/manual.html
맨아래 간단히 설명되어 있습니다.
 - PAPER에서 토폴로지 뷰를 사용하기 위해서는 SCOUTER 2.0 이상을 사용하여야 하며 java agent의 counter_interaction_enabled 옵션이 true 로 설정되어야 합니다.

**Comment by mindplates** [comment]
토폴로지 데이터는 수신이 된 것 같습니다. 다만 그래프를 그리는데 먼가 스크맂트 오류가 있을 것 같은데요.

혹시 가능하시면 스크린샷 이외에 개발자 도구에 콘솔 창에 표시된 에러 정보 좀 주시면 감사하겠습니다~~

**Comment by gogomasaru** [comment]
http://ip:port/scouter/v1/info/counter-model 401 (Unauthorized) 

아래 부분에서 에러납니다.
raven.js:1348 
-> return origSend.apply(this, arguments);

**Comment by mindplates** [comment]
넵 감사합니다. 저녁에 확인해서 수정하겠습니다!!

**Comment by gogomasaru** [comment]
빠른 수정 감사합니다.

금일 확인 해본 부분입니다.
1. XLOG
1) TIME RANGE -> search -> 1시간 이상 설정 (예 1시간 30분)
2) XLOG에 XLOG NOT SUPPORTED in this range. (1시간까지니 정상인 상황)
3) REAL TIME으로 변경할 경우 CPU, 메모리, Service count,  TPS 등 다시 그래프 나옴.
4) XLOG는 XLOG NOT SUPPORTED in this range. 상태로 계속 있음 
(1.9했을때는 정상으로 트랜잭션 점이 다시 나왔습니다. 1.9일때는 구간이 1시간만 있었으니. )
5) 새로 고침해야 다시 나옴.

2. 토플로지
1) PIN 고정안하면 3분 정도 후에 구석으로 몰림. 
2) 재세팅 후 pin 고정해도 몇십초에 한번씩 구석으로 몰림. (자세한건 동영상 확보하면 다시 말씀드리겠습니다.)

**Comment by mindplates** [comment]
위 1, 2번 
현재 개발 브렌치에 해당 버그 수정하였습니다. 
다음 릴리즈때 반영하겠습니다.
감사합니다!

**Comment by mindplates** [comment]
2.1.320 릴리즈하였습니다.
제보해주신 버그를 수정하였습니다.
더불어, 아이콘이 안나오는 경우는 데이터를 확인해봐야할 필요가 있어서,
기능 중에 '컨트롤 + 시프트 + u' 버튼을 클릭하면, 마스터 정보가 나옵니다.
해당 팝업 상단의 복사 버튼 클릭하셔서, 알려주시면 추가적으로 확인해보겠습니다.
다시 한번 제보 감사드립니다!

**Comment by gogomasaru** [comment]
신규 버전에 수정된 내용 확인했습니다. 감사합니다.

아이콘은 신규버전에서 육각형체 -> 서류? 서랍같은걸로 변경됐네요.
위에 말씀하신 마스터 정보 입니다.


{"objects":[{"objType":"linux","objFamily":"host","objHash":"-2028590978","objName":"/spmlwass01","address":"182.195.81.24","version":"2.0.0 2018-09-28 05:14 GMT","alive":true,"lastWakeUpTime":"1539147468455","tags":{"detected":"linux","counter":"1.2505013"}},{"objType":"jboss","objFamily":"javaee","objHash":"-2045619908","objName":"/spmlwass01/1","address":"182.195.81.24","version":"2.0.0 2018-09-28 05:14 GMT","alive":true,"lastWakeUpTime":"1539147468118","tags":{"ADC":false,"detected":"jboss","counter":"0"}},{"objType":"linux","objFamily":"host","objHash":"1247237161","objName":"/spsfwass01","address":"182.195.81.27","version":"2.0.0 2018-09-28 05:14 GMT","alive":true,"lastWakeUpTime":"1539147468606","tags":{"detected":"linux","counter":"1.2521303"}},{"objType":"jboss","objFamily":"javaee","objHash":"710634233","objName":"/spsfwass01/1","address":"182.195.81.27","version":"2.0.0 2018-09-28 05:14 GMT","alive":true,"lastWakeUpTime":"1539147468089","tags":{"ADC":false,"detected":"jboss","counter":"0"}},{"objType":"linux","objFamily":"host","objHash":"1713804210","objName":"/spwass01","address":"182.195.81.22","version":"2.0.0 2018-09-28 05:14 GMT","alive":true,"lastWakeUpTime":"1539147468085","tags":{"detected":"linux","counter":"2.8041353"}},{"objType":"jboss","objFamily":"javaee","objHash":"-1108458934","objName":"/spwass01/1","address":"182.195.81.22","version":"2.0.0 2018-09-28 05:14 GMT","alive":true,"lastWakeUpTime":"1539147467849","tags":{"ADC":false,"detected":"jboss","counter":"0"}}],"config":{"servers":[{"protocol":"http","address":"apm.stage.samsung.net","port":6188,"authentification":"bearer","default":false},{"protocol":"http","address":"apm.stage.samsung.net","port":"18080","authentification":"bearer","default":true}],"interval":2000,"alertInterval":60,"numberFormat":"0,0.0","decimalPoint":1,"dateFormat":"%Y-%m-%d","timeFormat":"%H:%M:%S","minuteFormat":"%H:%M","theme":"theme-blue/white","colorType":"white","graph":{"color":"instance","width":2,"opacity":0.7,"fill":"N","fillOpacity":0.4,"curve":"curveCatmullRom","break":"Y"},"alert":{"notification":"Y"},"range":{"shortHistoryRange":360,"shortHistoryStep":10,"longHistoryRange":720,"longHistoryStep":60},"xlog":{"normal":{"rows":5,"columns":5,"opacity":0.7,"sampling":100,"fills":{"D_0_2":{"color":"#0062B1"},"D_1_2":{"color":"#0062B1"},"D_2_0":{"color":"#0062B1"},"D_2_1":{"color":"#0062B1"},"D_2_2":{"color":"#0062B1"},"D_2_3":{"color":"#0062B1"},"D_2_4":{"color":"#0062B1"},"D_3_2":{"color":"#0062B1"},"D_4_2":{"color":"#0062B1"}}},"async":{"rows":5,"columns":5,"opacity":0.7,"sampling":100,"fills":{"D_0_2":{"color":"#888"},"D_1_2":{"color":"#888"},"D_2_0":{"color":"#888"},"D_2_1":{"color":"#888"},"D_2_2":{"color":"#888"},"D_2_3":{"color":"#888"},"D_2_4":{"color":"#888"},"D_3_2":{"color":"#888"},"D_4_2":{"color":"#888"}}},"error":{"rows":5,"columns":5,"opacity":0.7,"sampling":100,"fills":{"D_0_2":{"color":"#9F0500"},"D_1_2":{"color":"#9F0500"},"D_2_0":{"color":"#9F0500"},"D_2_1":{"color":"#9F0500"},"D_2_2":{"color":"#9F0500"},"D_2_3":{"color":"#9F0500"},"D_2_4":{"color":"#9F0500"},"D_3_2":{"color":"#9F0500"},"D_4_2":{"color":"#9F0500"}}}},"fonts":[{"val":"Bungee","name":"Bungee","generic":"cursive","type":"display"},{"val":"Righteous","name":"Righteous","generic":"cursive","type":"display"},{"val":"Mina","name":"Mina","generic":"sans-serif","type":"sans-serif"},{"val":"Nanum Gothic","name":"Nanum Gothic","generic":"sans-serif","type":"sans-serif"},{"val":"Noto Sans","name":"Noto Sans","generic":"sans-serif","type":"sans-serif"},{"val":"Nanum Gothic Coding","name":"Nanum Gothic Coding","generic":"monospace","type":"monospace"},{"val":"Cousine","name":"Cousine","generic":"monospace","type":"monospace"},{"val":"Space Mono","name":"Space Mono","generic":"monospace","type":"monospace"},{"val":"Kavivanar","name":"Kavivanar","generic":"cursive","type":"Handwriting"},{"val":"Handlee","name":"Handlee","generic":"cursive","type":"Handwriting"}],"fontSetting":{"basic":"Righteous","menu":"Bungee","axis":"Bungee","tooltip":"Righteous","profiler":"Righteous"}},"template":{"boxes":null,"layouts":null},"counterInfo":{"families":[{"name":"host","counters":[{"name":"Cpu","displayName":"CPU","unit":"%","totalizable":false,"icon":"cpu.png","master":true,"familyName":"host"},{"name":"SysCpu","displayName":"CPU | Sys","unit":"%","totalizable":false,"icon":"cpu.png","master":false,"familyName":"host"},{"name":"UserCpu","displayName":"CPU | User","unit":"%","totalizable":false,"icon":"cpu.png","master":false,"familyName":"host"},{"name":"DiskReadBytes","displayName":"Disk | ReadBytes","unit":"bytes/sec","totalizable":false,"icon":"disk_read.png","master":false,"familyName":"host"},{"name":"DiskWriteBytes","displayName":"Disk | WriteBytes","unit":"bytes/sec","totalizable":false,"icon":"disk_write.png","master":false,"familyName":"host"},{"name":"Mem","displayName":"Memory","unit":"%","totalizable":false,"icon":"memory.png","master":false,"familyName":"host"},{"name":"MemU","displayName":"Memory | ActualUsed","unit":"MB","totalizable":false,"icon":"memory.png","master":false,"familyName":"host"},{"name":"MemA","displayName":"Memory | Avaliable","unit":"MB","totalizable":false,"icon":"memory.png","master":false,"familyName":"host"},{"name":"MemT","displayName":"Memory | Total","unit":"MB","totalizable":false,"icon":"memory.png","master":false,"familyName":"host"},{"name":"TcpStatCLS","displayName":"Net | CLOSE_WAIT","unit":"cnt","totalizable":false,"icon":"drop.png","master":false,"familyName":"host"},{"name":"TcpStatEST","displayName":"Net | ESTABLISHED","unit":"cnt","totalizable":false,"icon":"time_read.png","master":false,"familyName":"host"},{"name":"TcpStatFIN","displayName":"Net | FIN_WAIT","unit":"cnt","totalizable":false,"icon":"time_read.png","master":false,"familyName":"host"},{"name":"NetInBound","displayName":"Net | InBound","unit":"cnt","totalizable":false,"icon":"bytes_recv.png","master":false,"familyName":"host"},{"name":"NetOutBound","displayName":"Net | OutBound","unit":"cnt","totalizable":false,"icon":"bytes_recv.png","master":false,"familyName":"host"},{"name":"NetRxBytes","displayName":"Net | RX Bytes","unit":"bytes/sec","totalizable":false,"icon":"packet_recv.png","master":false,"familyName":"host"},{"name":"TcpStatTIM","displayName":"Net | TIME_WAIT","unit":"cnt","totalizable":false,"icon":"time_read.png","master":false,"familyName":"host"},{"name":"NetTxBytes","displayName":"Net | TX Bytes","unit":"bytes/sec","totalizable":false,"icon":"packet_sent.png","master":false,"familyName":"host"},{"name":"Swap","displayName":"Swap","unit":"%","totalizable":false,"icon":"swap.png","master":false,"familyName":"host"},{"name":"PageIn","displayName":"Swap | PageIn","unit":"page","totalizable":false,"icon":"swap.png","master":false,"familyName":"host"},{"name":"PageOut","displayName":"Swap | PageOut","unit":"page","totalizable":false,"icon":"swap.png","master":false,"familyName":"host"},{"name":"SwapT","displayName":"Swap | Total","unit":"MB","totalizable":false,"icon":"swap.png","master":false,"familyName":"host"},{"name":"SwapU","displayName":"Swap | Used","unit":"MB","totalizable":false,"icon":"swap.png","master":false,"familyName":"host"}]},{"name":"javaee","counters":[{"name":"ActiveService","displayName":"Active Service","unit":"cnt","totalizable":true,"icon":"act_service.png","master":true,"familyName":"javaee"},{"name":"ApiTimeByService","displayName":"API Time by service","unit":"ms","totalizable":false,"icon":"time.png","master":false,"familyName":"javaee"},{"name":"Elapsed90%","displayName":"Elapsed 90%","unit":"ms","totalizable":false,"icon":"time.png","master":false,"familyName":"javaee"},{"name":"ElapsedTime","displayName":"Elapsed Time","unit":"ms","totalizable":false,"icon":"time.png","master":false,"familyName":"javaee"},{"name":"ErrorRate","displayName":"Error Rate","unit":"%","totalizable":true,"icon":"rate.png","master":false,"familyName":"javaee"},{"name":"FdUsage","displayName":"File Descriptor","unit":"cnt","totalizable":false,"icon":"memory.png","master":false,"familyName":"javaee"},{"name":"GcCount","displayName":"GC Count","unit":"cnt","totalizable":true,"icon":"gc.png","master":false,"familyName":"javaee"},{"name":"GcTime","displayName":"GC Time","unit":"ms","totalizable":false,"icon":"gc.png","master":false,"familyName":"javaee"},{"name":"HeapTotal","displayName":"Heap Total","unit":"MB","totalizable":false,"icon":"memory.png","master":false,"familyName":"javaee"},{"name":"HeapTotUsage","displayName":"Heap Total Usage","unit":"MB","totalizable":false,"icon":"memory.png","master":false,"familyName":"javaee"},{"name":"HeapUsed","displayName":"Heap Used","unit":"MB","totalizable":false,"icon":"memory.png","master":false,"familyName":"javaee"},{"name":"PermPercent","displayName":"Perm %","unit":"%","totalizable":false,"icon":"memory.png","master":false,"familyName":"javaee"},{"name":"PermUsed","displayName":"Perm Used","unit":"MB","totalizable":false,"icon":"memory.png","master":false,"familyName":"javaee"},{"name":"ProcCpu","displayName":"ProcessCpu","unit":"%","totalizable":false,"icon":"cpu.png","master":false,"familyName":"javaee"},{"name":"QueuingTime","displayName":"Queuing Time","unit":"ms","totalizable":false,"icon":"time.png","master":false,"familyName":"javaee"},{"name":"RecentUser","displayName":"Recent User","unit":"cnt","totalizable":true,"icon":"visitor.png","master":false,"familyName":"javaee"},{"name":"ServiceCount","displayName":"Service Count","unit":"cnt/min","totalizable":true,"icon":"service_count.png","master":false,"familyName":"javaee"},{"name":"SqlTimeByService","displayName":"SQL Time by service","unit":"ms","totalizable":false,"icon":"time.png","master":false,"familyName":"javaee"},{"name":"TPS","displayName":"TPS","unit":"tps","totalizable":true,"icon":"transaction.png","master":false,"familyName":"javaee"}]},{"name":"datasource","counters":[{"name":"ConnActive","displayName":"Conn Active","unit":"cnt","totalizable":true,"icon":"conn_act.png","master":true,"familyName":"datasource"},{"name":"ConnIdle","displayName":"Conn Idle","unit":"cnt","totalizable":true,"icon":"conn_idle.png","master":false,"familyName":"datasource"},{"name":"ConnMax","displayName":"Conn Max","unit":"cnt","totalizable":true,"icon":"database_go.png","master":false,"familyName":"datasource"}]},{"name":"reqproc","counters":[{"name":"BytesReceived","displayName":"Bytes Received","unit":"bytes","totalizable":true,"icon":"bytes_recv.png","master":false,"familyName":"reqproc"},{"name":"BytesSent","displayName":"Bytes Sent","unit":"bytes","totalizable":true,"icon":"bytes_sent.png","master":true,"familyName":"reqproc"},{"name":"ErrorCount","displayName":"Error Count","unit":"cnt","totalizable":true,"icon":"error_count.png","master":false,"familyName":"reqproc"},{"name":"ProcessingTime","displayName":"Processing Time","unit":"sec","totalizable":true,"icon":"proc_time.png","master":false,"familyName":"reqproc"},{"name":"RequestCount","displayName":"Request Count","unit":"cnt","totalizable":true,"icon":"req_count.gif","master":false,"familyName":"reqproc"}]},{"name":"batch","counters":[{"name":"BatchEnd","displayName":"Batch Accumulate End","unit":"cnt","totalizable":true,"icon":"service_count.png","master":false,"familyName":"batch"},{"name":"BatchEndNoSignal","displayName":"Batch Accumulate End(No Signal)","unit":"cnt","totalizable":true,"icon":"service_count.png","master":false,"familyName":"batch"},{"name":"BatchStart","displayName":"Batch Accumulate Start","unit":"cnt","totalizable":true,"icon":"service_count.png","master":false,"familyName":"batch"},{"name":"BatchService","displayName":"Batch Service","unit":"cnt","totalizable":true,"icon":"service_count.png","master":false,"familyName":"batch"}]},{"name":"aws","counters":[{"name":"Cpu","displayName":"CPU","unit":"%","totalizable":false,"icon":"cpu.png","master":true,"familyName":"aws"},{"name":"Mem","displayName":"Memory","unit":"%","totalizable":false,"icon":"memory.png","master":false,"familyName":"aws"},{"name":"RequestCount","displayName":"Request Count","unit":"cnt","totalizable":true,"icon":"req_count.gif","master":false,"familyName":"aws"}]}],"objTypesMap":{"linux":{"name":"linux","familyName":"host","displayName":"Linux","icon":null,"subObject":false},"windows":{"name":"windows","familyName":"host","displayName":"Windows","icon":null,"subObject":false},"osx":{"name":"osx","familyName":"host","displayName":"OSX","icon":null,"subObject":false},"host":{"name":"host","familyName":"host","displayName":"Host","icon":null,"subObject":false},"tomcat":{"name":"tomcat","familyName":"javaee","displayName":"Tomcat","icon":null,"subObject":false},"java":{"name":"java","familyName":"javaee","displayName":"Java","icon":null,"subObject":false},"jboss":{"name":"jboss","familyName":"javaee","displayName":"JBoss","icon":null,"subObject":false},"jetty":{"name":"jetty","familyName":"javaee","displayName":"Jetty","icon":null,"subObject":false},"resin":{"name":"resin","familyName":"javaee","displayName":"Resin","icon":null,"subObject":false},"batch":{"name":"batch","familyName":"batch","displayName":"Batch","icon":null,"subObject":false},"aws":{"name":"aws","familyName":"aws","displayName":"AWS","icon":null,"subObject":false},"datasource":{"name":"datasource","familyName":"datasource","displayName":"DataSource","icon":null,"subObject":true},"reqproc":{"name":"reqproc","familyName":"reqproc","displayName":"RequestProc","icon":null,"subObject":true}},"familyNameIcon":{"host":null,"javaee":null,"batch":null,"aws":null,"datasource":null,"reqproc":null}}}

**Comment by mindplates** [comment]
소중한 정보 감사합니다. 2.2.326 버전에 적용되었습니다!
