### ISSUE TITLE
XLOGBAR ShowCount와 CONFIG시 겹침

### ISSUE THREAD

**Issue by playok** [mindplates/scouter-paper#97]
안녕하세요.

이상증상이 하나 보여서 알려드립니다.

테스트 환경
paper 버전 : 2.1.301

![image](https://user-images.githubusercontent.com/253674/46322885-5613df80-c626-11e8-9e8b-22422655e2b9.png)

![image](https://user-images.githubusercontent.com/253674/46322913-83f92400-c626-11e8-955a-13eae516371d.png)

XLOGBAR에서 SHOW COUNT 옵션을 활성화 한후 CONFIG를 하면 depth차이인지 COUNT LABEL이 CONFIG 상단에 위치하며 위젯의 이동액션만 일어날뿐 버튼등에 대한 마우스 Action이 일어나지 않습니다.

**Comment by mindplates** [comment]
저녁에 확인해서 바로 수정 하도록 하겠습니다!!
